# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-09 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombreyapellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=13)),
                ('email', models.EmailField(blank=True, max_length=20)),
            ],
        ),
    ]
