# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-09 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menuentrada',
            fields=[
                ('id_menuentrada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('observacion', models.TextField(max_length=70, verbose_name='Observaci\xf3n')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Importe $')),
            ],
        ),
        migrations.CreateModel(
            name='menuespecial',
            fields=[
                ('id_menuespecial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('observacion', models.TextField(max_length=70, verbose_name='Observaci\xf3n')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Importe $')),
            ],
        ),
        migrations.CreateModel(
            name='menuprincipal',
            fields=[
                ('id_menuprincipal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('observacion', models.TextField(max_length=70, verbose_name='Observaci\xf3n')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Importe $')),
            ],
        ),
    ]
