# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-09 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaseosa',
            name='presentacion',
            field=models.CharField(choices=[('500cc', '500 CC'), ('1L', '1 Litro'), ('1,5Lts', '1,5 Litros'), ('2Lts', '2 Litros'), ('2,25Lts', '2,25 Litros')], max_length=20),
        ),
    ]
