# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-09 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0002_auto_20200609_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='aguamineral',
            fields=[
                ('id_aguamineral', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=10, verbose_name='Marca')),
                ('presentacion', models.CharField(choices=[('500cc', '500 CC'), ('1L', '1 Litro'), ('1,5Lts', '1,5 Litros'), ('2Lts', '2 Litros'), ('2,25Lts', '2,25 Litros')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='aguasaborizada',
            fields=[
                ('id_aguasaborizada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=10, verbose_name='Marca')),
                ('presentacion', models.CharField(choices=[('500cc', '500 CC'), ('1L', '1 Litro'), ('1,5Lts', '1,5 Litros'), ('2Lts', '2 Litros'), ('2,25Lts', '2,25 Litros')], max_length=20)),
            ],
        ),
    ]
